### ISSUE TITLE
Error:Uncaught translation error

### ISSUE THREAD

**Issue by pateelhs** [dev-prajwal21/CustomerSupportDesk#1]
Information:Gradle tasks [:app:assembleDebug]

Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/zza;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/zzd;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzac;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzc;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzk;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzv;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzv$zza;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzv$zza$zza;
Error:Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/internal/zzw;
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Translation has been interrupted
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --multi-dex --output /Users/pateelhs_agile/Downloads/CustomerSupportDesk-master/app/build/intermediates/transforms/dex/debug/folders/1000/1f/main /Users/pateelhs_agile/.android/build-cache/c6bf9444b0286447bef8aa5a71273362f33c7d72/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/390cb7ea24e591438416be7ac19068d69fa0cbe7/output/jars/classes.jar /Users/pateelhs_agile/Downloads/CustomerSupportDesk-master/customersupportdesk/build/intermediates/bundles/default/classes.jar /Users/pateelhs_agile/Downloads/CustomerSupportDesk-master/app/build/intermediates/classes/debug /Users/pateelhs_agile/.android/build-cache/2cd00b11da5878c7a1d825e505ac26d0684aa9b1/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/ae8a7829e5afefc9784df87526ecf73236543fb9/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/b14ab20fc8c1c0a3171ba654338d417cdf44beab/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/ced632ae0c0bb40eff5b8e13509f8944d7e7e73e/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/75e319910e5b0a18f390075b8d46e627f95cf73d/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/ccd5ad478a3585725ef6eb2f8510dfff28a626d5/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/875e229415a25e27096a2cb3867da94b098295a6/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/fd3c3b632df4dfe65dec6ad4fbdfc01eb349595c/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/7d2492a03d1b7dab20585ccaf4cd3d84665bb424/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/8eee0d3ce1ad80f345a7b96fe34e11a29cded558/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/c97e32b2eb92435dc40a5ceaa17ed7ea4a20999a/output/jars/classes.jar /Users/pateelhs_agile/.gradle/caches/modules-2/files-2.1/com.github.bumptech.glide/glide/3.7.0/9e9eeaf9948ee4d6c3ab354e8dc14368f16994a4/glide-3.7.0.jar /Users/pateelhs_agile/.android/build-cache/7f39f788f0ac31f7c0b02c04f6a46d1d014374bc/output/jars/classes.jar /Users/pateelhs_agile/Library/Android/sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/constraint-layout-solver-1.0.2.jar /Users/pateelhs_agile/.android/build-cache/4c3f5229c78b9805f45fd42055bc884ede2ffb43/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/d4252839dcb848075845a6b2536fd248b184d261/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/f9485bb1a65b6f6ea02547b5093bc5540dc90185/output/jars/classes.jar /Users/pateelhs_agile/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/25.3.1/support-annotations-25.3.1.jar /Users/pateelhs_agile/.android/build-cache/c36fd4a40198ec6e8c941cad0b8bcc4b0bac38cb/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/ad22de34a46e79e8cef889039fae30fa4ff1be55/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/7bc8edb2b0e2c576d544b3c3f3df6c5cf2b36982/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/5bfeb091689d462d7bdd85ef5e243a519dc1bd32/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/4b3fbbc7149c28cde699d5c8598ce8878d9743b7/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/2538a1636adf2306205369c458b609f4d04cf151/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/f9abf9dd3f959bfea0273e9a1137cf2ce31f849b/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/5644867eab0d475497e0175333306ab519fd423e/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/21674a40c0a421d5442b726b6e1627a8b43de144/output/jars/classes.jar /Users/pateelhs_agile/.android/build-cache/8b0a9c52b42559ba4625006c715a8b0acddcbe7b/output/jars/classes.jar}
Information:BUILD FAILED
Information:Total time: 38.124 secs
Information:11 errors
Information:1 warning
Information:See complete output in console

**Comment by ghost** [comment]
Hi pateelhs,
                   You need to add your firebase project json to app folder and then run the project.
