### ISSUE TITLE
Sugestion: Localize every text so we can translate it to other language.

### ISSUE THREAD

**Issue by kishannareshpal** [dev-prajwal21/CustomerSupportDesk#3]
Some text are not stringed. Such as:
> "No complaints to show"
> "No suggestions to show"
> "No feedback to show"

> "Check your internet connection"
>"Loading..."

> "Post/send complaint"
> "Post/send suggestion"
> "Post/send feedback"

**Comment by ghost** [comment]
Hi kishannareshpal,
                                Will surely consider your suggestions and reflect the same in the future update to the library.
